// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SystemTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Просмотр ошибок начального окна
        /// </summary>
        public void CheckErrors()
        {
            #region Variable Declarations
            WinButton uIВставитьButton = this.UITestingWindow.UIВставитьWindow.UIВставитьButton;
            WinButton uIОКButton = this.UIERRORWindow.UIОКWindow.UIОКButton;
            WinButton uIЗапускButton = this.UITestingWindow.UIЗапускWindow.UIЗапускButton;
            WinButton uIВыходButton = this.UITestingWindow.UIВыходWindow.UIВыходButton;
            #endregion

            // Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
            ApplicationUnderTest uITestingWindow = ApplicationUnderTest.Launch(this.CheckErrorsParams.UITestingWindowExePath, this.CheckErrorsParams.UITestingWindowAlternateExePath);

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(107, 24));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(59, 23));

            // Щелкните "Запуск!" кнопка
            Mouse.Click(uIЗапускButton, new Point(130, 36));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(59, 15));

            // Щелкните "Выход" кнопка
            Mouse.Click(uIВыходButton, new Point(217, 25));
        }
        
        /// <summary>
        /// Ищем максимальное в массиве
        /// </summary>
        public void CheckMaxFinding()
        {
            #region Variable Declarations
            WinEdit uIInputFieldEdit = this.UITestingWindow.UIInputFieldWindow.UIInputFieldEdit;
            WinButton uIВставитьButton = this.UITestingWindow.UIВставитьWindow.UIВставитьButton;
            WinButton uIЗапускButton = this.UITestingWindow.UIЗапускWindow.UIЗапускButton;
            WinButton uIОКButton = this.UIERRORWindow.UIОКWindow.UIОКButton;
            WinRadioButton uIМаксимальныйэлементRadioButton = this.UITestingWindow.UIМаксимальныйэлементWindow.UIМаксимальныйэлементRadioButton;
            WinEdit uIElemCountFieldEdit = this.UITestingWindow.UIElemCountFieldWindow.UIElemCountFieldEdit;
            WinEdit uIMaxOrMinFieldEdit = this.UITestingWindow.UIMaxOrMinFieldWindow.UIMaxOrMinFieldEdit;
            WinButton uIВыходButton = this.UITestingWindow.UIВыходWindow.UIВыходButton;
            #endregion

            // Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
            ApplicationUnderTest uITestingWindow = ApplicationUnderTest.Launch(this.CheckMaxFindingParams.UITestingWindowExePath, this.CheckMaxFindingParams.UITestingWindowAlternateExePath);

            // Тип "1" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(147, 21));

            // Тип "2" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText1;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(112, 23));

            // Тип "3" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText2;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(116, 31));

            // Тип "4" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText3;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(122, 31));

            // Тип "5" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText4;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(129, 11));

            // Тип "154" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText5;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(135, 17));

            // Тип "111" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText6;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(128, 20));

            // Тип "132" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText7;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(114, 19));

            // Тип "2453" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText8;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(104, 21));

            // Тип "23412" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMaxFindingParams.UIInputFieldEditText9;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(109, 23));

            // Щелкните "Запуск!" кнопка
            Mouse.Click(uIЗапускButton, new Point(127, 38));

            // Щелкните "ОК" кнопка
            Mouse.Click(uIОКButton, new Point(48, 20));

            // Выбор "Максимальный элемент" переключатель
            uIМаксимальныйэлементRadioButton.Selected = this.CheckMaxFindingParams.UIМаксимальныйэлементRadioButtonSelected;

            // Щелкните "Запуск!" кнопка
            Mouse.Click(uIЗапускButton, new Point(215, 27));

            Assert.AreEqual("7", uIElemCountFieldEdit.Text, $"Max count exp 7 now {uIElemCountFieldEdit.Text}");
            Assert.AreEqual("154", uIMaxOrMinFieldEdit.Text, $"Max exp 154 now {uIMaxOrMinFieldEdit.Text}");

            // Щелкните "Выход" кнопка
            Mouse.Click(uIВыходButton, new Point(95, 15));
        }
        
        /// <summary>
        /// Ищем минимальный элемент
        /// </summary>
        public void CheckMinFinding()
        {
            #region Variable Declarations
            WinEdit uIInputFieldEdit = this.UITestingWindow.UIInputFieldWindow.UIInputFieldEdit;
            WinButton uIВставитьButton = this.UITestingWindow.UIВставитьWindow.UIВставитьButton;
            WinRadioButton uIМинимальныйэлементRadioButton = this.UITestingWindow.UIМинимальныйэлементWindow.UIМинимальныйэлементRadioButton;
            WinButton uIЗапускButton = this.UITestingWindow.UIЗапускWindow.UIЗапускButton;
            WinEdit uIElemCountFieldEdit = this.UITestingWindow.UIElemCountFieldWindow.UIElemCountFieldEdit;
            WinEdit uIMaxOrMinFieldEdit1 = this.UITestingWindow.UIMaxOrMinFieldWindow.UIMaxOrMinFieldEdit1;
            WinButton uIВыходButton = this.UITestingWindow.UIВыходWindow.UIВыходButton;
            #endregion

            // Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
            ApplicationUnderTest uITestingWindow = ApplicationUnderTest.Launch(this.CheckMinFindingParams.UITestingWindowExePath, this.CheckMinFindingParams.UITestingWindowAlternateExePath);

            // Тип "1" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(69, 7));

            // Тип "2" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText1;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(58, 12));

            // Тип "3" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText2;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(81, 29));

            // Тип "4" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText3;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(72, 12));

            // Тип "5" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText4;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(72, 14));

            // Тип "154" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText5;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(67, 28));

            // Тип "111" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText6;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(85, 4));

            // Тип "132" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText7;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(96, 13));

            // Тип "2453" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText8;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(93, 12));

            // Тип "23412" в "inputField" надпись
            uIInputFieldEdit.Text = this.CheckMinFindingParams.UIInputFieldEditText9;

            // Щелкните "Вставить" кнопка
            Mouse.Click(uIВставитьButton, new Point(78, 15));

            // Выбор "Минимальный элемент" переключатель
            uIМинимальныйэлементRadioButton.Selected = this.CheckMinFindingParams.UIМинимальныйэлементRadioButtonSelected;

            // Щелкните "Запуск!" кнопка
            Mouse.Click(uIЗапускButton, new Point(145, 25));

            Assert.AreEqual("7", uIElemCountFieldEdit.Text, $"Min count exp 7 now {uIElemCountFieldEdit.Text}");
            Assert.AreEqual("1", uIMaxOrMinFieldEdit1.Text, $"Max exp 1 now {uIMaxOrMinFieldEdit1.Text}");

            // Щелкните "Выход" кнопка
            Mouse.Click(uIВыходButton, new Point(144, 19));
        }
        
        #region Properties
        public virtual CheckErrorsParams CheckErrorsParams
        {
            get
            {
                if ((this.mCheckErrorsParams == null))
                {
                    this.mCheckErrorsParams = new CheckErrorsParams();
                }
                return this.mCheckErrorsParams;
            }
        }
        
        public virtual CheckMaxFindingParams CheckMaxFindingParams
        {
            get
            {
                if ((this.mCheckMaxFindingParams == null))
                {
                    this.mCheckMaxFindingParams = new CheckMaxFindingParams();
                }
                return this.mCheckMaxFindingParams;
            }
        }
        
        public virtual CheckMinFindingParams CheckMinFindingParams
        {
            get
            {
                if ((this.mCheckMinFindingParams == null))
                {
                    this.mCheckMinFindingParams = new CheckMinFindingParams();
                }
                return this.mCheckMinFindingParams;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UITestingWindow UITestingWindow
        {
            get
            {
                if ((this.mUITestingWindow == null))
                {
                    this.mUITestingWindow = new UITestingWindow();
                }
                return this.mUITestingWindow;
            }
        }
        
        public UIERRORWindow UIERRORWindow
        {
            get
            {
                if ((this.mUIERRORWindow == null))
                {
                    this.mUIERRORWindow = new UIERRORWindow();
                }
                return this.mUIERRORWindow;
            }
        }
        #endregion
        
        #region Fields
        private CheckErrorsParams mCheckErrorsParams;
        
        private CheckMaxFindingParams mCheckMaxFindingParams;
        
        private CheckMinFindingParams mCheckMinFindingParams;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UITestingWindow mUITestingWindow;
        
        private UIERRORWindow mUIERRORWindow;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "CheckErrors"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class CheckErrorsParams
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowExePath = "C:\\Users\\arago\\OneDrive\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowAlternateExePath = "%OneDrive%\\Рабочий стол\\LabsForTesting.exe";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "CheckMaxFinding"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class CheckMaxFindingParams
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowExePath = "C:\\Users\\arago\\OneDrive\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowAlternateExePath = "%OneDrive%\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Тип "1" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText = "1";
        
        /// <summary>
        /// Тип "2" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText1 = "2";
        
        /// <summary>
        /// Тип "3" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText2 = "3";
        
        /// <summary>
        /// Тип "4" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText3 = "4";
        
        /// <summary>
        /// Тип "5" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText4 = "5";
        
        /// <summary>
        /// Тип "154" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText5 = "154";
        
        /// <summary>
        /// Тип "111" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText6 = "111";
        
        /// <summary>
        /// Тип "132" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText7 = "132";
        
        /// <summary>
        /// Тип "2453" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText8 = "2453";
        
        /// <summary>
        /// Тип "23412" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText9 = "23412";
        
        /// <summary>
        /// Выбор "Максимальный элемент" переключатель
        /// </summary>
        public bool UIМаксимальныйэлементRadioButtonSelected = true;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "CheckMinFinding"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class CheckMinFindingParams
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowExePath = "C:\\Users\\arago\\OneDrive\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowAlternateExePath = "%OneDrive%\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Тип "1" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText = "1";
        
        /// <summary>
        /// Тип "2" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText1 = "2";
        
        /// <summary>
        /// Тип "3" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText2 = "3";
        
        /// <summary>
        /// Тип "4" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText3 = "4";
        
        /// <summary>
        /// Тип "5" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText4 = "5";
        
        /// <summary>
        /// Тип "154" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText5 = "154";
        
        /// <summary>
        /// Тип "111" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText6 = "111";
        
        /// <summary>
        /// Тип "132" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText7 = "132";
        
        /// <summary>
        /// Тип "2453" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText8 = "2453";
        
        /// <summary>
        /// Тип "23412" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText9 = "23412";
        
        /// <summary>
        /// Выбор "Минимальный элемент" переключатель
        /// </summary>
        public bool UIМинимальныйэлементRadioButtonSelected = true;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "RecordedMethod1"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowExePath = "C:\\Users\\arago\\OneDrive\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Запуск "%OneDrive%\Рабочий стол\LabsForTesting.exe"
        /// </summary>
        public string UITestingWindowAlternateExePath = "%OneDrive%\\Рабочий стол\\LabsForTesting.exe";
        
        /// <summary>
        /// Тип "1" в "inputField" надпись
        /// </summary>
        public string UIInputFieldEditText = "1";
        
        /// <summary>
        /// Выбор "Минимальный элемент" переключатель
        /// </summary>
        public bool UIМинимальныйэлементRadioButtonSelected = true;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UITestingWindow : WinWindow
    {
        
        public UITestingWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Testing";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public UIВставитьWindow UIВставитьWindow
        {
            get
            {
                if ((this.mUIВставитьWindow == null))
                {
                    this.mUIВставитьWindow = new UIВставитьWindow(this);
                }
                return this.mUIВставитьWindow;
            }
        }
        
        public UIЗапускWindow UIЗапускWindow
        {
            get
            {
                if ((this.mUIЗапускWindow == null))
                {
                    this.mUIЗапускWindow = new UIЗапускWindow(this);
                }
                return this.mUIЗапускWindow;
            }
        }
        
        public UIВыходWindow UIВыходWindow
        {
            get
            {
                if ((this.mUIВыходWindow == null))
                {
                    this.mUIВыходWindow = new UIВыходWindow(this);
                }
                return this.mUIВыходWindow;
            }
        }
        
        public UIInputFieldWindow UIInputFieldWindow
        {
            get
            {
                if ((this.mUIInputFieldWindow == null))
                {
                    this.mUIInputFieldWindow = new UIInputFieldWindow(this);
                }
                return this.mUIInputFieldWindow;
            }
        }
        
        public UIМаксимальныйэлементWindow UIМаксимальныйэлементWindow
        {
            get
            {
                if ((this.mUIМаксимальныйэлементWindow == null))
                {
                    this.mUIМаксимальныйэлементWindow = new UIМаксимальныйэлементWindow(this);
                }
                return this.mUIМаксимальныйэлементWindow;
            }
        }
        
        public UIMaxOrMinFieldWindow UIMaxOrMinFieldWindow
        {
            get
            {
                if ((this.mUIMaxOrMinFieldWindow == null))
                {
                    this.mUIMaxOrMinFieldWindow = new UIMaxOrMinFieldWindow(this);
                }
                return this.mUIMaxOrMinFieldWindow;
            }
        }
        
        public UIМинимальныйэлементWindow UIМинимальныйэлементWindow
        {
            get
            {
                if ((this.mUIМинимальныйэлементWindow == null))
                {
                    this.mUIМинимальныйэлементWindow = new UIМинимальныйэлементWindow(this);
                }
                return this.mUIМинимальныйэлементWindow;
            }
        }
        
        public UIElemCountFieldWindow UIElemCountFieldWindow
        {
            get
            {
                if ((this.mUIElemCountFieldWindow == null))
                {
                    this.mUIElemCountFieldWindow = new UIElemCountFieldWindow(this);
                }
                return this.mUIElemCountFieldWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIВставитьWindow mUIВставитьWindow;
        
        private UIЗапускWindow mUIЗапускWindow;
        
        private UIВыходWindow mUIВыходWindow;
        
        private UIInputFieldWindow mUIInputFieldWindow;
        
        private UIМаксимальныйэлементWindow mUIМаксимальныйэлементWindow;
        
        private UIMaxOrMinFieldWindow mUIMaxOrMinFieldWindow;
        
        private UIМинимальныйэлементWindow mUIМинимальныйэлементWindow;
        
        private UIElemCountFieldWindow mUIElemCountFieldWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIВставитьWindow : WinWindow
    {
        
        public UIВставитьWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "inputButton";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinButton UIВставитьButton
        {
            get
            {
                if ((this.mUIВставитьButton == null))
                {
                    this.mUIВставитьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIВставитьButton.SearchProperties[WinButton.PropertyNames.Name] = "Вставить";
                    this.mUIВставитьButton.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIВставитьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIВставитьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIЗапускWindow : WinWindow
    {
        
        public UIЗапускWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "startButton";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗапускButton
        {
            get
            {
                if ((this.mUIЗапускButton == null))
                {
                    this.mUIЗапускButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIЗапускButton.SearchProperties[WinButton.PropertyNames.Name] = "Запуск!";
                    this.mUIЗапускButton.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIЗапускButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗапускButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIВыходWindow : WinWindow
    {
        
        public UIВыходWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "exit";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinButton UIВыходButton
        {
            get
            {
                if ((this.mUIВыходButton == null))
                {
                    this.mUIВыходButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIВыходButton.SearchProperties[WinButton.PropertyNames.Name] = "Выход";
                    this.mUIВыходButton.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIВыходButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIВыходButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIInputFieldWindow : WinWindow
    {
        
        public UIInputFieldWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "inputField";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinEdit UIInputFieldEdit
        {
            get
            {
                if ((this.mUIInputFieldEdit == null))
                {
                    this.mUIInputFieldEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIInputFieldEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Введите новый элемент массива";
                    this.mUIInputFieldEdit.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIInputFieldEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIInputFieldEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIМаксимальныйэлементWindow : WinWindow
    {
        
        public UIМаксимальныйэлементWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "maxRadioButton";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIМаксимальныйэлементRadioButton
        {
            get
            {
                if ((this.mUIМаксимальныйэлементRadioButton == null))
                {
                    this.mUIМаксимальныйэлементRadioButton = new WinRadioButton(this);
                    #region Условия поиска
                    this.mUIМаксимальныйэлементRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Максимальный элемент";
                    this.mUIМаксимальныйэлементRadioButton.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIМаксимальныйэлементRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIМаксимальныйэлементRadioButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIMaxOrMinFieldWindow : WinWindow
    {
        
        public UIMaxOrMinFieldWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "maxOrMinField";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinEdit UIMaxOrMinFieldEdit
        {
            get
            {
                if ((this.mUIMaxOrMinFieldEdit == null))
                {
                    this.mUIMaxOrMinFieldEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIMaxOrMinFieldEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Максимальный:";
                    this.mUIMaxOrMinFieldEdit.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIMaxOrMinFieldEdit;
            }
        }
        
        public WinEdit UIMaxOrMinFieldEdit1
        {
            get
            {
                if ((this.mUIMaxOrMinFieldEdit1 == null))
                {
                    this.mUIMaxOrMinFieldEdit1 = new WinEdit(this);
                    #region Условия поиска
                    this.mUIMaxOrMinFieldEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "Минимальный:";
                    this.mUIMaxOrMinFieldEdit1.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIMaxOrMinFieldEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIMaxOrMinFieldEdit;
        
        private WinEdit mUIMaxOrMinFieldEdit1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIМинимальныйэлементWindow : WinWindow
    {
        
        public UIМинимальныйэлементWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "minRadioButton";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIМинимальныйэлементRadioButton
        {
            get
            {
                if ((this.mUIМинимальныйэлементRadioButton == null))
                {
                    this.mUIМинимальныйэлементRadioButton = new WinRadioButton(this);
                    #region Условия поиска
                    this.mUIМинимальныйэлементRadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "Минимальный элемент";
                    this.mUIМинимальныйэлементRadioButton.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIМинимальныйэлементRadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIМинимальныйэлементRadioButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIElemCountFieldWindow : WinWindow
    {
        
        public UIElemCountFieldWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "elemCountField";
            this.WindowTitles.Add("Testing");
            #endregion
        }
        
        #region Properties
        public WinEdit UIElemCountFieldEdit
        {
            get
            {
                if ((this.mUIElemCountFieldEdit == null))
                {
                    this.mUIElemCountFieldEdit = new WinEdit(this);
                    #region Условия поиска
                    this.mUIElemCountFieldEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Искомых элементов:";
                    this.mUIElemCountFieldEdit.WindowTitles.Add("Testing");
                    #endregion
                }
                return this.mUIElemCountFieldEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIElemCountFieldEdit;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIERRORWindow : WinWindow
    {
        
        public UIERRORWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ERROR";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public UIОКWindow UIОКWindow
        {
            get
            {
                if ((this.mUIОКWindow == null))
                {
                    this.mUIОКWindow = new UIОКWindow(this);
                }
                return this.mUIОКWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIОКWindow mUIОКWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОКWindow : WinWindow
    {
        
        public UIОКWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("ERROR");
            #endregion
        }
        
        #region Properties
        public WinButton UIОКButton
        {
            get
            {
                if ((this.mUIОКButton == null))
                {
                    this.mUIОКButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIОКButton.SearchProperties[WinButton.PropertyNames.Name] = "ОК";
                    this.mUIОКButton.WindowTitles.Add("ERROR");
                    #endregion
                }
                return this.mUIОКButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIОКButton;
        #endregion
    }
}
